alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gh='git hist'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gl='git ls-files'

alias ls='ls --color=auto -h'
alias le='ll'
alias sbl='/opt/sublime_text/sublime_text'
alias rgrep='grep -RI'
alias ip='ip -c'
alias cp='cp -r'
alias scp='scp -r'
alias copy='xclip -sel clip'
alias py='python3.7'
alias du='du -d1 -h'
alias cpwd='pwd | xclip -sel clip'
