alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gh='git hist'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gl='git ls-files'

alias la='command ls -la --color=auto -v'
alias ls='ls --color=auto -h'
alias le='command ls -l --color=auto -v'
alias sbl='/opt/sublime_text/sublime_text'
alias rg='grep -RI'
alias ip='ip -c'
alias cp='cp -r'
alias scp='scp -r'
alias copy='xclip -sel clip'
alias py='python3.8'
alias du='du -d1 -h'
alias cpwd='pwd | xclip -sel clip'
alias cal='ncal -C'
alias gr='grep'
alias rt='sudo zsh'
alias sudo='sudo '
alias ps='ps axu'
alias df='df -h'
alias fd='find -name'
