alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gh='git hist'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gl='git ls-files'

alias le='ls -l'
alias sublime='/opt/sublime_text/sublime_text'
alias rgrep='grep -RI'
alias ip='ip -c'
